default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost
  user: postgres
  password: 3110saitou
  port: 5434

development:
  <<: *default
  database: knowhow_index_development

test:
  <<: *default
  database: knowhow_index_test

production:
  <<: *default
  database: knowhow_index_production
